export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAIL = 'GET_TASKS_FAIL';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';

export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SET_THEME = 'SET_THEME';

export const CHECK_ALIAS_AVAILABILITY_SUCCESS = 'CHECK_ALIAS_AVAILABILITY_SUCCESS';
export const CHECK_ALIAS_AVAILABILITY_FAIL = 'CHECK_ALIAS_AVAILABILITY_FAIL';

export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_FAIL = 'ADD_LIST_FAIL';

export const CHECK_EXISTING_ALIAS_SUCCESS = 'CHECK_EXISTING_ALIAS_SUCCESS';
export const CHECK_EXISTING_ALIAS_FAIL = 'CHECK_EXISTING_ALIAS_FAIL';