exports.light = {
  backgroundColor: '#fffeed',
  listBackground: 'rgba(148, 148, 148, 0.3)',
  fontFamily: 'Actor',
  headingColor: '#d1fbff',
  headingTextShadowColor: '#ebebeb',
  subHeadingColor: '#696969',
  subHeadingTextShadowColor: '#ebebeb',
  taskTextShadowColor: '#ebebeb',
  taskBackgroundColor: 'rgba(209, 251, 255, .7)',
  taskNameColor: '#696969',
  taskNameBorderColor: '#ffffc4',
  taskDateColor: '#696969',
  taskDateBorderColor: '#fefff0',
  doneButtonColor: '#696969',
  doneButtonBorderColor: '#ffffc4',
}

exports.dark = {
  backgroundColor: '#000000',
  listBackground: 'rgba(235, 235, 235, 0.2)',
  fontFamily: 'Actor',
  headingColor: '#f2ddce',
  headingTextShadowColor: '#f2ddce',
  taskTextShadowColor: '#ebebeb',
  taskBackgroundColor: 'rgba(0, 0, 0, .7)',
  taskNameColor: '#81deb5',
  taskNameBorderColor: '#81deb5',
  taskDateColor: '#f59fb3',
  taskDateBorderColor: '#f59fb3',
  doneButtonColor: '#ffffc4',
  doneButtonBorderColor: '#ffffc4',
}

exports.classy = {
  backgroundImage: 'url("https://i.postimg.cc/Kzk0KkMp/IMG-2284-1-1.png")',
  largeBackgroundImage: 'url("https://i.postimg.cc/KYfXxqcS/IMG-2284-1-2.png")',
  backgroundColor: '',
  listBackground: 'rgba(219, 140, 159, 0.3)',
  fontFamily: 'Italiana',
  headingColor: '#696969',
  headingTextShadowColor: '#f0e4e7',
  subHeadingColor: '#cdf7d9',
  subHeadingTextShadowColor: '#ffffff',
  taskTextShadowColor: '#ffffff',
  taskBackgroundColor: 'rgba(89, 86, 87, .8)',
  taskNameColor: '#f0e4e7',
  taskNameBorderColor: '#f5edf7',
  taskDateColor: '#f7fad7',
  taskDateBorderColor: '#f7fad7',
  doneButtonColor: '#cdf7d9',
  doneButtonBorderColor: '#cdf7d9',
}

exports.nature = {
  backgroundImage: 'url("https://i.postimg.cc/MZRzLjvy/IMG-5228-1.png")',
  largeBackgroundImage: 'url("https://i.postimg.cc/x8rnC9FJ/IMG-5228-1-1.png")',
  listBackground: 'rgba(115, 115, 115, 0.3)',
  fontFamily: 'Neucha',
  headingColor: '#5a8561',
  headingTextShadowColor: '#ebebeb',
  subHeadingColor: '#8f522c',
  subHeadingTextShadowColor: '#ebebeb',
  taskTextShadowColor: '#ebebeb',
  taskBackgroundColor: 'rgba(90, 133, 97, .8)',
  taskNameColor: '#ebebeb',
  taskNameBorderColor: '#b87e5a',
  taskDateColor: '#ebebeb',
  taskDateBorderColor: '#a3756a',
  doneButtonColor: '#ebebeb',
  doneButtonBorderColor: '#949151',
}

exports.floral = {
  backgroundImage: 'url("https://i.postimg.cc/rpdsCtgK/IMG-5035.jpg")',
  listBackground: 'rgba(247, 247, 247, 0.3)',
  fontFamily: 'La Belle Aurore',
  headingColor: '#675f7d',
  headingTextShadowColor: '#ebebeb',
  subHeadingColor: '#9e6582',
  subHeadingTextShadowColor: '#ebebeb',
  taskTextShadowColor: '#ebebeb',
  taskBackgroundColor: 'rgba(103, 95, 125, .7)',
  taskNameColor: '#ebebeb',
  taskNameBorderColor: '#fefff0',
  taskDateColor: '#ebebeb',
  taskDateBorderColor: '#fefff0',
  doneButtonColor: '#ebebeb',
  doneButtonBorderColor: '#f7b2eb',
}